### ISSUE TITLE
Selfies broken with RStudio and OSX Mojave

### ISSUE THREAD

**Issue by muschellij2** [swarm-lab/Rvision#18]
```r
my_stream <- stream(0)   # 0 will start your default webcam in general. 
my_selfie <- readNext(my_stream)
plot(my_selfie)
release(my_stream)
```
causes RStudio to crash in OSX Mojave due to permissions issues.  This should be fixed in future release https://github.com/rstudio/rstudio/pull/4581

**Comment by sjmgarnier** [comment]
@muschellij2 Which version of RStudio? It works perfectly here with 1.2.1335.

**Comment by muschellij2** [comment]
Do you have OSX Mojave?
John

**Comment by sjmgarnier** [comment]
Yes.

**Comment by muschellij2** [comment]
I had 1.2.1502 and it would simply crash when trying.   I made some steps to fix in case it comes up https://github.com/muschellij2/recordscreen#errors-with-mac-osx-mojave-and-rstudio.  Now that it's in my approved camera apps, it's fine.  If I uncheck it, I get
```bash
OpenCV: error in [AVCaptureDeviceInput initWithDevice:error:]
2019-04-17 18:58:43.533 rsession[85958:3972130] OpenCV: Cannot use FaceTime HD Camera
OpenCV: camera failed to properly initialize!
```
which is to be expected as I've de-authorized the app.

**Comment by muschellij2** [comment]
What do you see in System Preferences → Security & Privacy?  Do you have RStudio in there as here?

<img width="640" alt="Screen Shot 2019-04-17 at 7 00 00 PM" src="https://user-images.githubusercontent.com/1075118/56326203-1c7a7000-6143-11e9-9db3-36173f06a1b2.png">

**Comment by sjmgarnier** [comment]
Yes

**Comment by muschellij2** [comment]
Well as long as that's the case, it's fine.  For some reason, it wasn't popping up with a request for authorization and would crash as a result.

**Comment by sjmgarnier** [comment]
I guess I'll add a not about this in the help and tutorials, just in case.

**Comment by sjmgarnier** [comment]
@muschellij2 BTW, it looks like recordscreen is shaping up nicely.

**Comment by jeroen** [comment]
See https://github.com/opencv/opencv/issues/14258
