### ISSUE TITLE
can not install Rvision on Ubuntu18

### ISSUE THREAD

**Issue by klobenmann** [swarm-lab/Rvision#21]
Hi,
I just tried to install Rvision on Ubuntu18, but I get the following error, anyone an idea how to solve it? ROpenCVLite is installed (see frist lines):

> library(ROpenCVLite)
> isOpenCVInstalled()
[1] TRUE
> devtools::install_github("swarm-lab/Rvision")
Downloading GitHub repo swarm-lab/Rvision@master
✔  checking for file ‘/tmp/Rtmp53XylF/remotes127c3a5f9c96/swarm-lab-Rvision-f793cb3/DESCRIPTION’ ...
─  preparing ‘Rvision’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘Rvision/man/figures’
─  building ‘Rvision_0.3.5.tar.gz’
   
Installing package into ‘/home/thorsten/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
* installing *source* package ‘Rvision’ ...
+ set -e
+ /usr/lib/R/bin/Rscript -e 'if (!ROpenCVLite::isOpenCVInstalled()) {
  message("OpenCV is not installed on this system. It will be installed now.")
  ROpenCVLite::installOpenCV(force = TRUE)
}'
ARGUMENT '~+~~+~message("OpenCV~+~is~+~not~+~installed~+~on~+~this~+~system.~+~It~+~will~+~be~+~installed~+~now.")' __ignored__

ARGUMENT '~+~~+~ROpenCVLite::installOpenCV(force~+~=~+~TRUE)' __ignored__

ARGUMENT '}' __ignored__

Error: unexpected end of input
Execution halted
ERROR: configuration failed for package ‘Rvision’
* removing ‘/home/thorsten/R/x86_64-pc-linux-gnu-library/3.4/Rvision’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/Rtmp53XylF/file127c37a8705d/Rvision_0.3.5.tar.gz’ had non-zero exit status

**Comment by sjmgarnier** [comment]
@klobenmann I don't think you can install ROpenCVLite on R 3.4. I would suggest trying with 3.5, or better 3.6.

**Comment by klobenmann** [comment]
I updated R to 3.6 now it works. Thank you very much.
