### ISSUE TITLE
geoTiff image (float) input

### ISSUE THREAD

**Issue by tseehaus** [swarm-lab/Rvision#22]
Hi,
my aim is to edit geoTiff image (images with a geographic coordinate system information) using Rvision. 
The values are in float format. Is there an option to use "float" values in Rvision? 
My idea for a work around would be to scale the values to the full range of the INT.  
However, I can only use 8bit. 16 bit would allow me much more precision for the scaling and the subsequent rescaling to float.
how to set the data format to 16bits using the function "image". is it possibel?

**Comment by sjmgarnier** [comment]
@tseehaus Floats should be supported now.
