### ISSUE TITLE
Problem reading frames

### ISSUE THREAD

**Issue by wrathematics** [swarm-lab/Rvision#23]
First, thanks for the helpful package.

I would like to convert a video into a matrix where each column is a frame, where I treat each frame as a vector of values 0-255. As an example I'm using the file `centaur_1.mpg` here http://hubblesource.stsci.edu/sources/video/clips/ (direct link to video file http://hubblesource.stsci.edu/sources/video/clips/details/images/centaur_1.mpg)

I'd like to do something like this

```r
library(Rvision)

mpeg2mat = function(video_file)
{
  vid = video(video_file)
  d = dim(vid)
  m = d[1]*d[2]
  n = d[3]
  mat = matrix(0L, m, n)
  
  for (j in 1:n)
  {
    img = readFrame(vid, j)
    img_gray = changeColorSpace(img, "GRAY")
    vec = as.integer(img_gray[])
    mat[, j] = vec
  }
  
  mat
}

mat = mpeg2mat("centaur_1.mpg")
```

However, when trying to read frame 19 I see

```
Error in x$readFrame(pos) : Could not read the image matrix.
```

Checking the dimension of the `Rcpp_Video` object, it reports 422 frames, which sounds right.

Looking at the frames I am able to grab (1-18), when I plot the grayscale image, it looks fine. But if I create a bitmap, the image is incorrect:

```r
library(Rvision)

video_file = "centaur_1.mpg"
vid = video(video_file)
img = readFrame(vid, 18)

img2bmp = function(img, file)
{
  img_gray = changeColorSpace(img, "GRAY")
  img_gray_array = (img_gray[])
  
  bmp_header = paste0("P2\n", paste(dim(img_gray_array), collapse=" "), "\n255\n")
  cat(bmp_header, file=file, append=FALSE)
  write.table(img_gray_array, file=file, append=TRUE, row.names=FALSE, col.names=FALSE, sep=" ")
}

img2bmp(img, "test.bmp")
```

I'm not an image/video person so I'm not really sure what's going on here. Any help you could give would be greatly appreciated.

**Comment by sjmgarnier** [comment]
@wrathematics OpenCV has troubles positioning the read head or estimating the true number of frames (if you use readNext, you'll see that there is actually 420 frames, not 422) with some encoding formats. It looks like the encoding format of your video is one of these. Unfortunately, this is not something I can easily fix on my end. Your best option is to encode your video in a more OpenCV-friendly format.

**Comment by wrathematics** [comment]
Oh, interesting. I'll try it with some different test videos.

Thanks for the quick response!

**Comment by sjmgarnier** [comment]
@wrathematics Thanks to @muschellij2 in #25, it looks like the issue is caused by the default API chosen by OpenCV when reading your video. If you try:

```vid <- video("centaur_1.mpg", api = "AVFOUNDATION")```

then it works. 

Note also that the first frame is at index 0, not 1.
