### ISSUE TITLE
live streaming and take a snapshots

### ISSUE THREAD

**Issue by maalid** [swarm-lab/Rvision#24]
Hi, I was wondering if there is a way to run live streaming and take a snapshot.

I mean, running:

my_stream <- stream(index = 0)
my_selfie <- readNext(my_stream)
plot(my_selfie)
release(my_stream)

only takes the snapshot. It would be amazing if I can have a live image and be able to take a snapshot.

Thanks in advance for your response!

**Comment by sjmgarnier** [comment]
@maalid Do you mean live view? You can do this with the `display()` function and a `while` loop.

**Comment by maalid** [comment]
@sjmgarnier Thanks for your reply!

Yes, live view.

I tried the `while` loop but I could not figure how to get the snapshot (on demand and not every `interval`) while the loop is running.

This is the code I used (I modified the `timelapse` function):

    launchWebCam <- function (obj, 
                              displayName = "My display",
                              objeto = "Imagen",
                              outputFolder,
                              interval = 1, 
                              duration = Inf, 
                              delay = 2, 
                              height = 480,  
                              width = 640) 
    {
        if (!isStream(obj)) 
            stop("This is not a Stream object.")
        outputFolder <- suppressWarnings(normalizePath(outputFolder))
        if (!file.exists(outputFolder)) {
            message("The output folder does not exist. It will be created.")
            dir.create(outputFolder)
        }
        
        counter <- 0
        start <- .now()
        end <- start + duration * 1000
        while (.now() < end) {
            img <- obj$readNext()
            display(img, displayName, delay, height, width)
            fileName <- sprintf("%s_%s.png", objeto, chartr(" :-", "___", format(Sys.time(), "%F %X")))
            img$write(paste0(outputFolder, "/", fileName))
            counter <- counter + 1
            print(paste0("Last picture taken at: ", Sys.time()))
            Sys.sleep(((start + counter * interval * 1000) - .now())/1000)
        }
        NULL
    }
    
    my_stream <- stream(index = 0)
    launchWebCam(obj = my_stream, outputFolder = "Miguel/")
    release(my_stream)   
    destroyAllDisplays()


My final idea is to make a shiny app that shows live view, and allows to take snapshots on users demand. Any suggestions that help me to do it?

Thanks again in advance!

**Comment by sjmgarnier** [comment]
@maalid Re: Shiny. Check the `invalidateLater()` scheme. For instance, see line 127 here: https://github.com/swarm-lab/antCounteR/blob/master/inst/antCounteR/app.R. 

I'm closing this because it is not related to a bug or a feature request, but feel free to keep commenting here if you have other questions related to your application.

**Comment by maalid** [comment]
@sjmgarnier Thanks a lot! I will try your suggestion. It seems auspicious!
