### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by markdane** [swarm-lab/Rvision#27]
Hi,

I'm hoping to use your Rvision and ROpenCVLite packages for several projects but cannot complete the Rvision installation. I completed the instructions for installing ROpenCVLite and that seemed to go okay. Is there any guidance you can provide?

thanks,
Mark

This is the error message and session info:

>devtools::install_github("swarm-lab/Rvision")
Downloading GitHub repo swarm-lab/Rvision@master
✔  checking for file ‘/private/var/folders/0r/hh_t8j_s53s0kqb01gzt76ch3221b9/T/RtmpQL6ovs/remotesbbd507ac8f5/swarm-lab-Rvision-1c99261/DESCRIPTION’ ...
─  preparing ‘Rvision’: (434ms)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘Rvision/man/figures’
─  building ‘Rvision_0.3.6.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
* installing *source* package ‘Rvision’ ...
+ set -e
+ /Library/Frameworks/R.framework/Resources/bin/Rscript -e 'if (!ROpenCVLite::isOpenCVInstalled()) {
  cat("------------------ OPENCV NOT FOUND --------------------\n")
  cat("\n")
  cat("OpenCV was not found in your library. Please install OpenCV as follows:")
  cat("\n")
  cat("\n")
  cat("ROpenCVLite::installOpenCV()\n")
  cat("\n")
  cat("--------------------------------------------------------\n")
  cat("\n")
  stop("OpenCV not found.")
}'
ARGUMENT '~+~~+~cat("------------------~+~OPENCV~+~NOT~+~FOUND~+~--------------------' __ignored__

ARGUMENT '")' __ignored__

ARGUMENT '~+~~+~cat("' __ignored__

ARGUMENT '")' __ignored__

ARGUMENT '~+~~+~cat("OpenCV~+~was~+~not~+~found~+~in~+~your~+~library.~+~Please~+~install~+~OpenCV~+~as~+~follows:")' __ignored__

ARGUMENT '~+~~+~cat("' __ignored__

ARGUMENT '")' __ignored__

ARGUMENT '~+~~+~cat("' __ignored__

ARGUMENT '")' __ignored__

ARGUMENT '~+~~+~cat("ROpenCVLite::installOpenCV()' __ignored__

ARGUMENT '")' __ignored__

ARGUMENT '~+~~+~cat("' __ignored__

ARGUMENT '")' __ignored__

ARGUMENT '~+~~+~cat("--------------------------------------------------------' __ignored__

ARGUMENT '")' __ignored__

ARGUMENT '~+~~+~cat("' __ignored__

ARGUMENT '")' __ignored__

ARGUMENT '~+~~+~stop("OpenCV~+~not~+~found.")' __ignored__

ARGUMENT '}' __ignored__

Error: unexpected end of input
Execution halted
ERROR: configuration failed for package ‘Rvision’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision’
Error: Failed to install 'Rvision' from GitHub:
  (converted from warning) installation of package ‘/var/folders/0r/hh_t8j_s53s0kqb01gzt76ch3221b9/T//RtmpQL6ovs/filebbd31b2ec87/Rvision_0.3.6.tar.gz’ had non-zero exit status

> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ROpenCVLite_0.3.410

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        rstudioapi_0.10   magrittr_1.5      usethis_1.5.1     devtools_2.2.1   
 [6] pkgload_1.0.2     R6_2.4.1          rlang_0.4.2       tools_3.5.3       pkgbuild_1.0.6   
[11] parallel_3.5.3    packrat_0.5.0     sessioninfo_1.1.1 cli_1.1.0         withr_2.1.2      
[16] ellipsis_0.3.0    remotes_2.1.0     assertthat_0.2.1  digest_0.6.23     rprojroot_1.3-2  
[21] crayon_1.3.4      processx_3.4.1    callr_3.3.2       fs_1.3.1          ps_1.3.0         
[26] curl_4.2          testthat_2.3.0    glue_1.3.1        memoise_1.1.0     compiler_3.5.3   
[31] desc_1.2.0        backports_1.1.5   prettyunits_1.0.2

**Comment by apford07** [comment]
You don't say what platform you are on (Mac ?)
on non ubuntu linux including  Centos, Fedora, RedHat 
its is necessary to add a  link between installing opencv and Rvision

>  system(paste("pushd",file.path(.libPaths(), "opencv"), "; ln -s lib64 lib")
