### ISSUE TITLE
additional functions from opencv - Question

### ISSUE THREAD

**Issue by Atan1988** [swarm-lab/Rvision#28]
Thank you for this great package as well as RopenCVLite. 
I have been using opencv via reticulate, and it has the disadvantage of not able to utilize multi-processes due to reliance on embedded python. It is also simply great to have a R package to work with. 
Do you have plans to implement other functions into Rvision?  For example, getStructuringElement, erode, dilate, boundingRect, contourArea, approxPolyDP, threshold, etc.

In the RopenCVLite github page, you mentioned that it is possible to pull additional functions from openCV similar to what's done in the Rvision package.  Since I have never incorporated cpp into R packages, it is hard to figure out where to start.  What would be some good resources to learn how get started?

Thanks,
Allen

**Comment by sjmgarnier** [comment]
@Atan1988 Thanks for your message. ROpenCVLite/Rvision is largely the work of two people only (@muschellij2 and myself) who both have busy schedules, so any additional help will be more than welcome. 

To answer your questions:
1. All morphological operations (erode, dilate, etc.) are already available through the `morph` function. If you think it would be more convenient, it should be easy to create separate functions for each morphological operation that would call `morph` in the background. This only requires R knowledge.
2. The OpenCV `threshold` function is not implemented in Rvision at the moment but you can achieve most forms of thresholding by using combinations of the inequality signs (>, <, ≥, ≤) directly on an image.
3. If you'd like to see an OpenCV function be implemented in Rvision, the simplest thing that you can do at the moment is create feature requests on this repository. One feature request per desired function would make it easier for me to track what needs to be implemented and get to it when I find the time. 
4. If you'd like to be more involved and participate in the development of Rvision by providing additional OpenCV functionalities, I suggest you familiarize yourself with Rcpp first (http://www.rcpp.org/, http://adv-r.had.co.nz/Rcpp.html). It's the framework we use in the background to access the OpenCV functions. Once you're familiar with Rcpp, you can look into the Rvision codebase to see how we've exposed the OpenCV functions to R and try your hand at exposing new functions. Note, however, that I'm in no way a good programmer (I'm learning as I go) and the way I do things here is probably not the most recommended one :-)

**Comment by Atan1988** [comment]
Thank you for your reply! I will test the morph function, and open feature requests for the other desired functions to be exposed.  At the meantime, I will also try to get more familiar with Rcpp so I can better follow how you have exposed the OpenCV functions.
