### ISSUE TITLE
overlay plot on image/video

### ISSUE THREAD

**Issue by mingchangtsai** [swarm-lab/Rvision#31]
Hi,

I'd like to overlay a data plot onto a video, what is the easiest and/or efficient way to do that?

Here is my code, doesn't look efficient, especially saving it to a file and reading it as an image before writing it to the video
```
my_video <- video("tmp_video.MOV",api="ANY")
mydata <- read_csv("data.csv")

writer <- videoWriter("test.mp4", "H264", 25, 1080, 1920)
for (i in 1:100) {
  png('test.png')

# combined plot
  par(fig=c(0,1,0.3,1))
  plot(readNext(my_video))
  par(fig=c(0.2,0.8,0,0.5),mai=c(0.5,0,0.8,0),bty="n", new=TRUE)
  plot(x~time,mydata[(i+1):(i+10),],t='l',xlab="")
  dev.off()

  img2 <- Rvision::image("test.png")
  
  writeFrame(writer, img2)
}
release(writer)
```

thanks in advance for any suggestions.

**Comment by sjmgarnier** [comment]
@mingchangtsai This is not really a Rvision issue, so I'll close this now. But to answer your question, look into magick::image_graph and magick::image_data to transform your graph into an array that can then be fed into Rvision::image. Not tested and not sure it'll be faster than your current solution.
