### ISSUE TITLE
Failure to open video

### ISSUE THREAD

**Issue by apford07** [swarm-lab/Rvision#35]
I successfully used an earlier version of  Rvision on Centos7  but I get an error on opening a video on Centos8 and Fedora33 
Rvision version 0.4.1 
opencv version  4.5.0 
Other programs eg ffmpeg, openshot, firefox all  process video OK
```
> Veg <- video(system.file("sample_vid/Balloon.mp4", package = "Rvision"))

Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Could not open the video.
```
Can I enable more verbose messages to understand the problem ?
What other  information is needed ?

**Comment by Eli-S-Bridge** [comment]
I had the same or a similar issue.

`cat /etc/redhat-release  
CentOS Linux release 7.8.2003 (Core)`

`[ebridge@schooner2` jtest]$ R

R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(Rvision)
> file file file
[1] "TestClip.mp4"
> vid )
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) :
Could not open the video.`

**Comment by Eli-S-Bridge** [comment]
Now I'm getting same error on windows 10 when trying to use VideoWriter(). Same code works on a mac. Any insights would be useful.

**Comment by sjmgarnier** [comment]
@apford07 Sorry, I don't use CentOS so I won't be able to debug this.

**Comment by sjmgarnier** [comment]
@Eli-S-Bridge Please open a separate issue for the problem with Windows, with reproducible code if possible.

**Comment by apford07** [comment]
Could you give some suggestions on how I could debug it.

**Comment by sjmgarnier** [comment]
@sjmgarnier A first step would be to recompile OpenCV with `ROpenCVLite::installOpenCV()`. Prior to doing that, make sure that you have installed all the codec dev packages that are necessary to read that video.

**Comment by apford07** [comment]
It appears to have been fixed in 
Rvision     * 0.5.0   2021-03-10 [2] Github (swarm-lab/Rvision@6be14b3)
(it was also OK in 0.4.0)  problem seems to be only in 0.4.1

**Comment by sjmgarnier** [comment]
@apford07 I don't think that I have touched that part of the code since 0.4. I made a ton of changes to get to 0.5, maybe one of them fixed the bug you encountered.
