### ISSUE TITLE
Flipping of images

### ISSUE THREAD

**Issue by GxHam** [swarm-lab/Rvision#36]
Thank you so much for this great package. It handles my large tiff images with the highest efficiency out of all other R packages I tested.

I'd like to know if there is a function I can use to flip an image horizontally or vertically? I have been using the rotation code with great success, but am unsure how I can go about flipping an image.

**Comment by sjmgarnier** [comment]
@GxHam There is none at the moment but I'll add this as soon as I'm done with another project.

**Comment by sjmgarnier** [comment]
@GxHam It should work with the latest dev version of the package.
