### ISSUE TITLE
videoWriter error on windows 10

### ISSUE THREAD

**Issue by Eli-S-Bridge** [swarm-lab/Rvision#37]
Ported over from issue #35.

videoWriter throws an error on Windows 10.  

Some specs:
Device name	DESKTOP-LSMOPJM
Processor	Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor

Windows 10 Education Version 20H2
OS build 19042.746
Windows Feature Experience Pack 120.2212.551.0

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Here's some code that gives the error:

```
library(Rvision)

setwd("C:\\Users\\ebridge\\Documents\\lunaero\\apr2019")
file <- "ESB1_20190421072658.mp4"
vid <- video(file)
im <-  readFrame(vid, 10)
dim(im)
#1080 1920    3
plot(im)
#plot is OK, so far no problems

outVid <- videoWriter(outputFile = "Test_outVid.mp4",
                      fourcc = "avc1", fps = 25, height = 1080,
                      width= 1920, isColor = F, api = "ANY")

#Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
#  Could not open the output.
 

outVid <- videoWriter(outputFile = "C:\\Users\\ebridge\\Documents\\lunaero\\apr2019\\Test_outVid.mp4",
                      fourcc = "avc1", fps = 25, height = 1080,
                      width= 1920, isColor = F, api = "ANY")

#Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
#  Could not open the output.
```
Thanks for any help.

**Comment by sjmgarnier** [comment]
@Eli-S-Bridge What versions of Rvision and ROpenCVLite are you using?

**Comment by sjmgarnier** [comment]
@Eli-S-Bridge My best guess is that either the "avc1" codec is not supported on your computer (i.e. it wasn't present when ROpenCVLite compiled OpenCV) or that "Test_outVid.mp4" is already present at the location where you're trying to write (i.e. the file was created during a previous attempt and was not removed before the next attempt). I'm betting on the second option because OpenCV would have said something about the missing codec (at least it does on my Windows machine). OpenCV doesn't overwrite existing files and throws a "Could not open the output" error in such cases.

**Comment by Eli-S-Bridge** [comment]
Thanks for looking into this. I made sure that the the output file did not exist--That was not the issue. I was able to get videoWriter to work when the codec was set to MP4V. So that lets me move forward. I tried installing the AVC1 codec and then reinstalling Rvision. The avc1 codec still did not work. However, I have not tried recompiling OpenCV since the codec installation. I'll give that a shot at some point and update. 

Incidentally, when I tried the MP4V codec with videoWriter on my mac (where I've been having no problems whatsoever), I got the same error 

#Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
#  Could not open the output.

I switched back to avc1 and the error persisted. I then did an R restart, and the problem persisted. Then I ran some code that made use of other Rvision functions and videoWriter started working again. I did not change anything that I know of, and the output file name was the same (nothing was written until it finally worked). And both codecs are working now (avc1 and MP4V). So, I'm a bit baffled.

Sorry for the lack of repeatable code. I can't get the issue to repeat.

**Comment by sjmgarnier** [comment]
@Eli-S-Bridge Codecs are linked during OpenCV's compilation. You'll need to rerun `ROpenCVLite::installOpenCV()` and select `yes` when asked.
