### ISSUE TITLE
importing large TIFF videos

### ISSUE THREAD

**Issue by Cumol** [swarm-lab/Rvision#6]
Hello,

I stumbled upon your package because I was looking for a way to load large (4gb) tiff-videos that were generated from single images. The idea is to get them into a format that can be used to work with SCALPEL (an R-package for calcium imaging in neurons).

The vignette of SCALPEL described how the data should be formatted:

> The data should be a \(P \times T\) matrix, where \(P\) is the total number of pixels per image frame and \(T\) the number of frames of the video, for which the \((i,j)\)th element contains the fluorescence of the \(i\)th pixel in the \(j\)th frame. To create this matrix, you should vectorize each 2-dimensional image frame by concatenating the columns of the image frame.

Now I was wondering if it is possible to use Rvision for it.

When I simply try 
`
test <- video("path to file.tif")
`
I get an empty object (I guess?)

**Comment by sjmgarnier** [comment]
@Cumol Rvision `Video` objects are essentially C++ pointers towards OpenCV `VideoCapture` objects (plus some candy around to interface more easily with R). This is why they look like "empty" objects. Videos are actually not loaded in memory like a classical R object. 

To access a frame, you need to use the `readNext` (for the next frame) and `readFrame` (for an arbitrary frame) functions that will return an `Image` object, which is also a C++ pointer towards an OpenCV object (`Mat` in this case) and also not loaded directly into memory. To achieve what you want to do (if I understand it correctly), you can then transform each `Image` object into a R matrix using the `as.matrix` function, and then stack the matrices together. However, all these matrices will be in R's memory, so I hope your machine has a lot of RAM.

**Comment by Cumol** [comment]
@sjmgarnier I went on to check if I can use `readNext` to show one frame of the video (I guess the first?). According to the documentation all I need to give the function is the name of the object.

`library(Rvision)

test <- video("./registered.tif")

readNext(test)`

I get the following error:

> Error in obj$readNext() : Could not read the image matrix.

For `str(test)` I get the following:

> Reference class 'Rcpp_Video' [package "Rvision"] with 0 fields
 list()
 and 30 methods, of which 16 are  possibly relevant:
   codec, dim, finalize, fps, frame, get, initialize, isOpened, ncol, nframes,
   nrow, open, readFrame, readNext, release, set

Simply running `test` gives the following:

`C++ object <0x5630d93024d0> of class 'Video' <0x5630d92f60d0>`

I am getting the feeling that Rvision is not capable of dealing with .tif videos. Is that correct?

**Comment by sjmgarnier** [comment]
@Cumol I can't find anything about tiff videos online. Are you talking about multi page or multi frame tiff? Do you have a sample video that I could play with?

**Comment by Cumol** [comment]
It is a video generated with ImageJ from a few thousand TIFF files.

I cropped one of my videos (originally 12k frames) into 100, you can find it here:
https://nextcloud.cumol.org/index.php/s/38K4xBFrRu7Hw2M

**Comment by sjmgarnier** [comment]
@Cumol FYI, I've managed to create a function that reads a multi-image tiff and then returns a list of Rvision Image objects. You can then use sapply+as.matrix to convert them into the matrix you need. I have to write the documentation of the new function before pushing it to Github, but once it's done (probably tomorrow), the code to do what you want (I think) will look like this: 
```
img_list <- readMulti("path to file.tif")
img_matrix <- sapply(img_list, as.matrix)
```
For your 100 stack of images, this takes about half a second to load and convert the images into the R matrix on my laptop, and results in a 122mb matrix with 160544 rows (P) and 100 columns (T). If we extrapolate linearly, I expect you'll need about 1-2 minutes and 14Gb of RAM to load and hold the 12,000 frames.

**Comment by Cumol** [comment]
Wow, thank you! can't wait to try it out. Let me know once it is out!

**Comment by sjmgarnier** [comment]
@Cumol It should work now.

**Comment by Cumol** [comment]
I tried it out. Something weird happens with memory allocation during the process. I am on a 35Gb and 36core machine.

I tried it out with 1000 frames, resulting in 1.3Gb memory usage.

6300 frames (half the file) results in 8Gb memory usage.

When running the full 12600 frames the image reading seems to work but what comes after is problematic:

```
> system.time(img_list <- readMulti("./registered.tif"))
   user  system elapsed 
 25.669  23.269 375.122 
> system.time(img_matrix <- sapply(img_list, as.matrix))
Error: cannot allocate vector of size 15.1 Gb
Timing stopped at: 45.53 12.57 58.1
```
During the second step, memory usage shoots over the (probable) 16Gb taking all the memory. A few seconds after this R stops and crashes...

Any idea what is happening here?

**Comment by sjmgarnier** [comment]
@Cumol I'm not sure how sapply handles memory allocation in the background. It could be making copies of the very large matrix you're trying to create, which would use up all your memory very quickly. One workaround would be to preallocate the final matrix and then fill it up column by column with a good old-fashioned loop: 
```
img_list <- readMulti("path to file.tif")
img_matrix <- matrix(0.0, nrow = nrow(img_list[[1]]) * ncol(img_list[[1]]), ncol = length(img_list))

for (i in 1:ncol(img_matrix)) {
  img_matrix[, i] <- as.matrix(img_list[[i]])
}
```
For some reason, this is even 10-15% faster on my computer than the sapply version with the 100 frames sample that you provided me with.

**Comment by sjmgarnier** [comment]
@Cumol Any luck with the loop version?

**Comment by Cumol** [comment]
@sjmgarnier just tried it out and it works!!!! 👍 

It does the same behavior as sapply, taking up all memory, but does not present the error with a too large vector. After the operation is finished it goes to 16.2 Gb for the img_matrix and 27.4Mb for the img_list.

Thank you for the help!

I just noticed that the package I want to use wants a dgeMatrix (never heard about this before) looking like this (from an example file provided with the package):

```
Formal class 'dgeMatrix' [package "Matrix"] with 4 slots
  ..@ x       : num [1:450000] -0.5022 0.1315 -0.0789 0.8868 0.117 ...
  ..@ Dim     : int [1:2] 900 500
  ..@ Dimnames:List of 2
  .. ..$ : NULL
  .. ..$ : NULL
  ..@ factors : list()
```

I found out they can be created with the Matrix package but no idea how to turn a "normal" matrix into this one.

In this case, the 500 is the number of frames and 900 is the number of pixels (in a 30x30 image). In my case I have 12600 frames and 160544 pixel.

` num [1:160544, 1:12600] 1 2 1 1 1 1 1 1 1 1 ...`

Any clues?

**Comment by sjmgarnier** [comment]
@Cumol This goes beyond Rvision. I suggest you post your question on the R mailing list or Stackoverflow.

**Comment by Cumol** [comment]
@sjmgarnier thank you for your help! If its useful I can post my final script as a use case once I am there :)

**Comment by sjmgarnier** [comment]
@Cumol Might be more useful to post this where the users of the SCALPEL package can see it. I couldn't find a Github repo for it (except for the CRAN Github repo) but maybe you could get in touch with the package maintainer to get it posted on the package website (https://ajpete.com/software/).

**Comment by Cumol** [comment]
@sjmgarnier I am in contact with Ashley. No Github repo but maybe she could integrate that into her vignette on her website

**Comment by Cumol** [comment]
@sjmgarnier 

It seems like readMulti downscales the image to 6-bit, at least that is what happens when I load in a 16-bit dataset.

Could that be possible?

**Comment by sjmgarnier** [comment]
@Cumol A flag wasn't set properly in cv::imreadmulti (the OpenCV function on top of which readMulti is built). It's fixed now. 

Next time, could you please open a new issue for new problems like this one instead of continuing on a closed one? Thanks.

**Comment by Cumol** [comment]
Will do. Thanks for the fix!
