### ISSUE TITLE
stream error: raspberry cam no work

### ISSUE THREAD

**Issue by corsariovasco** [swarm-lab/Rvision#8]
Hello, 

I playing with python and opencv, in concrete with pipcamera,  but i see yours work and as I love R...i will test it...the installation into raspberry works me...R...libraries: 
ROpenCVLite and Rvision...
`ROpenCVLite::opencvVersion()`
"### Version: 3.4.1"
It is fine.
In the case of my first test... an image capture:
`my_stream <- Rvision::stream(0)`
"### Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) :
  Could not open the stream."
This is  not worked me.

I have used a raspberry cam and this working on pipcam and raspistill. In your library, have you any limited on cams?. 

Kind regards,

**Comment by sjmgarnier** [comment]
@corsariovasco I do not have the possibility to test the package on Raspberry Pi (I can only test it on Windows 10, Ubuntu-family Linux, and Mac OS X). Therefore I can't really help with this problem at the moment.

**Comment by cictourgune** [comment]
@sjmgarnier :-( Thanks...
what is your technological stack (IDE: atom, vs, R studio?. Might you tell me how to debug? ... Maybe I could collaborate. I could install R studio into raspberry and execute your source. That's enough!, i do not know it.

**Comment by corsariovasco** [comment]
@sjmgarnier  :-( Thanks...
what is your technological stack (IDE: atom, vs, R studio?. Might you tell me how to debug? ... Maybe I could collaborate. I could install R studio into raspberry and execute your source. That's enough!, i do not know it.

A question...
what is the origin the list of all supported APIs based on StreamClass?...the opencv has more but i do not found the definitions. Maybe the raspberry has its API own.

Kind regards,

**Comment by sjmgarnier** [comment]
@corsariovasco I develop using RStudio. 

Supported APIs should be detected by cmake when compiling OpenCV. It's possible some option must be activated when compiling on Raspberry. I won't have the time to investigate this myself before a while. Let me know if you find anything.
