### ISSUE TITLE
sm idea for rvision

### ISSUE THREAD

**Issue by amjiuzi** [swarm-lab/Rvision#9]
1. read images find their outlines and reset them in same size ,
further, transform image info into matrix ( like MNIST dataset) for image recognization
2. read videos and recognize moving obj by stream

can our Rvision work no.1 out now ??

**Comment by sjmgarnier** [comment]
@amjiuzi Thanks. 

For 1, without an example of what you mean by "outline", I'm not certain I understand what you want to do exactly. 
You can combine Rvision with TensorFlow for object recognition. See https://twitter.com/Md_Harris/status/962427019802955776 for an example. 

For 2, you can already do basic object tracking. See https://twitter.com/Md_Harris/status/962074959895040001 for example.
