### ISSUE TITLE
R session aborted

### ISSUE THREAD

**Issue by monviso** [swarm-lab/Rvision#93]
Hi, I have managed recently to install Rvision (thanks a lot Simon),

I can load images with `i2 <- Rvision::image(filename = "F:/Errocthy/MATRICE/images/21-23-07-2021/section3/11.30am/rgb/DJI_0007.jpg")`, with the object created being 
> i2
Class: image. 
Dimensions: 4000x3000.
Type: BGR, 3-channel, 8U.
GPU: FALSE.

Nonetheless, now R session aborts when trying to run any other function on that image. I have tried simply `plot()` or   `changeColorSpace()`. 

I have no detail on eventual errors occurring from R.

thanks

**Comment by sjmgarnier** [comment]
@monviso I can't reproduce the problem here. Can you please try the example provided with the `plot` function (see below)? 

```r
balloon <- image(system.file("sample_img/balloon1.png", package = "Rvision"))
plot(balloon)
```

Does the R session abort in this case as well? If not, would you mind sharing with me (garnier@njit.edu) one of the images that present this issue?

**Comment by monviso** [comment]
@sjmgarnier yes the session abort also with the sample image.

One thing that maybe is relevant is that once I run the `image` function the object balloon is created in the environment but has length=0 and size=0. The same applies to my images.

**Comment by sjmgarnier** [comment]
@monviso That is very odd. Let me run some tests and I'll get back to you when I can.

**Comment by sjmgarnier** [comment]
@monviso My tests are inconclusive. Everything works fine on my Windows 10 machine after a clean install of ROpenCVLite (from the updated CRAN version) and of Rvision (from this GitHub repo). Would you be open to a quick video call? It might help me assess the issue with your machine. If yes, just reach out to me at [garnier@njit.edu](mailto:garnier@njit.edu).

**Comment by sjmgarnier** [comment]
@monviso You're probably not interested anymore, but I believe this may be the solution to the problem you ran into: https://github.com/swarm-lab/trackR/issues/36#issuecomment-1862965967

**Comment by monviso** [comment]
@sjmgarnier Sorry for this late reply and thanks a lot. I was going through different way but Still interested. thanks a lot.

**Comment by sjmgarnier** [comment]
@monviso No problem. If you get a chance to try the fix, let me know if it works. A definitive fix should be published on CRAN as soon as they reopen the submission system after their holidays.
