### ISSUE TITLE
macOS Sonoma 14.5 installation issue

### ISSUE THREAD

**Issue by goterm** [swarm-lab/Rvision#96]
Hi,

**Describe the bug**
I do not manage to install Rvision .

**To Reproduce**
if (!require(devtools))
  install.packages("devtools")

brew install cmake

install.packages("devtools")
devtools::install_github("swarm-lab/ROpenCVLite")

I get: 
> ROpenCVLite::isOpenCVInstalled()
[1] TRUE
> ROpenCVLite::OpenCVPath()
[1] "/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/ROpenCV"

but when I run:
devtools::install_github("swarm-lab/Rvision")

I get: 
Error: package or namespace load failed for ‘Rvision’ in .doLoadActions(where, attach):
 error in load action .__A__.12 for package Rvision: Rcpp::loadModule(module = "methods_Display", what = TRUE, env = ns, : Unable to load module "methods_Display": invalid type/length (symbol/0) in vector allocation
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rvision’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/33/zpkyd6b91h57kjs4h93z8_1h0000gq/T//RtmpokBAaB/file1326d2e3342ee/Rvision_0.8.0.tar.gz’ had non-zero exit status
> 

any hint of what may be going on here?
thanks

**Comment by sjmgarnier** [comment]
@goterm I'm not sure. First, I would remove the development version of `ROpenCVLite` that you have installed and use instead the stable version available on CRAN: 

```r
ROpenCVLite::removeOpenCV()
remove.packages("ROpenCVLite")
install.packages("ROpenCVLite")
ROpenCVLite::installOpenCV()
```

Then, try to reinstall `Rvision`: 

```r
devtools::install_github("swarm-lab/Rvision")
```

**Comment by sjmgarnier** [comment]
@goterm It looks like a similar issue also happens in Windows (see #97). I haven't modified anything recently, so my best guess is that a recent update to Rcpp has broken something in Rvision. I'll investigate further when I get the chance.

**Comment by sjmgarnier** [comment]
@goterm Which version of R are you using?

**Comment by sjmgarnier** [comment]
@goterm I found the guilty function and pushed a fix in [09d65a9](https://github.com/swarm-lab/Rvision/commit/09d65a98f215feb5da2ca1d1e5815c25c8d5050f). I will push it to the main branch soon but you can already install it from the develop branch.

**Comment by goterm** [comment]
Hi,

thanks for the quick response. 

I am using R 4.4.0.

I tried the steps you suggested but now I can't even install OpenCV:

> install.packages("ROpenCVLite")
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.4/ROpenCVLite_4.90.1.tgz'
Content type 'application/x-gzip' length 55967 bytes (54 KB)
==================================================
downloaded 54 KB


The downloaded binary packages are in
	/var/folders/33/zpkyd6b91h57kjs4h93z8_1h0000gq/T//Rtmpt204co/downloaded_packages
> ROpenCVLite::installOpenCV()
OpenCV is not installed on this system. Would you like to install it now? This will take several minutes. 

1: yes
2: no

Selection: 1
OpenCV will be installed in /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/ROpenCV
Clearing install path.
trying URL 'https://github.com/opencv/opencv/archive/4.9.0.zip'
downloaded 38.4 MB

Error in utils::download.file(config$core, paste0(config$tmp_dir, "/opencv.zip")) : 
  download from 'https://github.com/opencv/opencv/archive/4.9.0.zip' failed
In addition: Warning message:
In utils::download.file(config$core, paste0(config$tmp_dir, "/opencv.zip")) :
  URL 'https://codeload.github.com/opencv/opencv/zip/refs/tags/4.9.0': Timeout of 60 seconds was reached
>

**Comment by sjmgarnier** [comment]
That's a download timeout error. Two options, your Internet connection is not fast or the download server is temporarily overwhelmed. You can increase the timeout with `options(timeout=100)` (for 100 seconds).
